### ISSUE TITLE
Plugin throws error in Jenkins

### ISSUE THREAD

**Issue by seetaramh** [trivago/cluecumber-report-plugin#103]
We have integrated Cluecumber reporting plugin for generating reports with jvm-parallel plugin. It works fine in local system and generates the report very well. When executed on Jenkins. It does not execute the goal. Below is the detailed exception.

```
[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting (report) on project cucumber: Execution report of goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting failed: Unable to load the mojo 'reporting' (or one of its required components) from the plugin 'com.trivago.rta:cluecumber-report-plugin:1.5.0': com.google.inject.ProvisionException: Guice provision errors:
[ERROR] 
[ERROR] 1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[ERROR] at com.trivago.cluecumber.CluecumberReportPlugin.class(CluecumberReportPlugin.java:55)
[ERROR] while locating com.trivago.cluecumber.CluecumberReportPlugin
[ERROR] at ClassRealm[plugin>com.trivago.rta:cluecumber-report-plugin:1.5.0, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting)
[ERROR] 
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting (report) on project cucumber: Execution report of goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting failed: Unable to load the mojo 'reporting' (or one of its required components) from the plugin 'com.trivago.rta:cluecumber-report-plugin:1.5.0'
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.jvnet.hudson.maven3.launcher.Maven3Launcher.main(Maven3Launcher.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.jvnet.hudson.maven3.agent.Maven3Main.launch(Maven3Main.java:181)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.maven.Maven3Builder.call(Maven3Builder.java:139)
        at hudson.maven.Maven3Builder.call(Maven3Builder.java:70)
        at hudson.remoting.UserRequest.perform(UserRequest.java:212)
        at hudson.remoting.UserRequest.perform(UserRequest.java:54)
        at hudson.remoting.Request$2.run(Request.java:369)
        at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution report of goal com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting failed: Unable to load the mojo 'reporting' (or one of its required components) from the plugin 'com.trivago.rta:cluecumber-report-plugin:1.5.0'
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:115)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 30 more
Caused by: org.apache.maven.plugin.PluginContainerException: Unable to load the mojo 'reporting' (or one of its required components) from the plugin 'com.trivago.rta:cluecumber-report-plugin:1.5.0'
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:488)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        ... 31 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: com.google.inject.ProvisionException: Guice provision errors:

1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.trivago.cluecumber.CluecumberReportPlugin.class(CluecumberReportPlugin.java:55)
  while locating com.trivago.cluecumber.CluecumberReportPlugin
  at ClassRealm[plugin>com.trivago.rta:cluecumber-report-plugin:1.5.0, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting)

1 error
      role: org.apache.maven.plugin.Mojo
  roleHint: com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:257)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        ... 32 more
Caused by: com.google.inject.ProvisionException: Guice provision errors:

1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.trivago.cluecumber.CluecumberReportPlugin.class(CluecumberReportPlugin.java:55)
  while locating com.trivago.cluecumber.CluecumberReportPlugin
  at ClassRealm[plugin>com.trivago.rta:cluecumber-report-plugin:1.5.0, parent: sun.misc.Launcher$AppClassLoader@4e25154f]
  while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.trivago.rta:cluecumber-report-plugin:1.5.0:reporting)

1 error
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:999)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
```

**Comment by laxersaz** [comment]
It looks like on Jenkins it is executed with an old Maven version. So you either need to
- update Maven on Jenkins or
- run it in a Docker container with a newer Maven version

**Comment by seetaramh** [comment]
Thanks so much!!! working fine now

**Comment by laxersaz** [comment]
Perfect 👍
