### ISSUE TITLE
Could not find a suitable constructor in CluecumberReportPlugin

### ISSUE THREAD

**Issue by RomaSha2009** [trivago/cluecumber-report-plugin#196]
Hi!
I receive an error after test run with cluecumber-report-plugin
I'm limited with Maven 3.0.4
I have tried to use old versions down to 0.1.1 and the issue was still present.

Here is a stack trace 

```
[INFO] --- cluecumber-report-plugin:2.0.1:reporting (report) @ MyProject ---
 25, 2019 5:36:09 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
WARNING: Error injecting: com.trivago.cluecumber.CluecumberReportPlugin
com.google.inject.ConfigurationException: Guice configuration errors:

1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
  at com.trivago.cluecumber.CluecumberReportPlugin.class(Unknown Source)
  while locating com.trivago.cluecumber.CluecumberReportPlugin

1 error
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:991)
        at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:950)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1000)
        at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
        at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
        at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
        at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
        at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
        at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
        at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:965)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1011)
        at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:961)
        at com.google.inject.Scopes$1$1.get(Scopes.java:59)
        at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
        at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:253)
        at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:245)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:20.345s
[INFO] Finished at: Thu Jul 25 17:36:09 EEST 2019
[INFO] Final Memory: 13M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:2.0.1:reporting (report) on project MyProject: Execution report of goal com.trivago.rta:cluecumber-report-plugin:2.0.1:reporting failed: Unable to load the m
ojo 'reporting' (or one of its required components) from the plugin 'com.trivago.rta:cluecumber-report-plugin:2.0.1': com.google.inject.ProvisionException: Guice provision errors:
[ERROR]
[ERROR] 1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
[ERROR] at com.trivago.cluecumber.CluecumberReportPlugin.class(Unknown Source)
[ERROR] while locating com.trivago.cluecumber.CluecumberReportPlugin
[ERROR] at ClassRealm[plugin>com.trivago.rta:cluecumber-report-plugin:2.0.1, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=com.trivago.rta:cluecumber-report-plugin:2.0.1:reporting)
[ERROR]
[ERROR] 1 error
[ERROR] role: org.apache.maven.plugin.Mojo
[ERROR] roleHint: com.trivago.rta:cluecumber-report-plugin:2.0.1:reporting
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

```

Here is my pom setup

```
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.22.0</version>
                <executions>
                    <execution>
                        <id>acceptance-test</id>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <properties>
                        <property>
                            <name>dataproviderthreadcount</name>
                            <value>10</value>
                        </property>
                    </properties>
                    <rerunFailingTestsCount>0</rerunFailingTestsCount>
                    <testFailureIgnore>true</testFailureIgnore>
                    <parallel>classes</parallel>
                    <reuseForks>false</reuseForks>
                    <includes>
                        <include>**/*RunCukeTestIT.java</include>
                    </includes>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.trivago.rta</groupId>
                <artifactId>cluecumber-report-plugin</artifactId>
                <version>2.0.1</version>
                <executions>
                    <execution>
                        <id>report</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>reporting</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sourceJsonReportDirectory>${project.build.directory}/cucumber-report.json</sourceJsonReportDirectory>
<generatedHtmlReportDirectory>${project.build.directory}/cucumberHtmlReport/</generatedHtmlReportDirectory>
                </configuration>
            </plugin>
```

Can anyone help me? What I'm doing wrong? In addition - I can't update Maven. Only 3.0.4

**Comment by laxersaz** [comment]
Your Maven version is too low (needs 3.3.9 at least). In the documentation this is also mentioned:
https://github.com/trivago/cluecumber-report-plugin#building
So if you cannot update Maven you either cannot use Cucumber or you run everything (or just a small Maven project with just Cluecumber in it) in a docker container that includes a higher Maven version.

**Comment by laxersaz** [comment]
A little background - Cluecumber uses Guice for dependency injection which is not present in older Maven versions.

**Comment by RomaSha2009** [comment]
I see. Thank you for your help!
