### ISSUE TITLE
Fails to run via bamboo

### ISSUE THREAD

**Issue by motivatedmind** [trivago/cluecumber-report-plugin#241]
**Describe the bug**
Fails to run via bamboo

**To Reproduce**
I added the plugin as below to my pom and it works perfectly in local however fails to run from bamboo. 

**Expected behavior**
Plugins runs as expected

**Attachments**
	Mar 19, 2020 2:57:28 PM org.sonatype.guice.bean.reflect.LoadedClass
	WARNING: Error injecting: com.trivago.cluecumber.CluecumberReportPlugin
	com.google.inject.ConfigurationException: Guice configuration errors:
	
	1) Could not find a suitable constructor in com.trivago.cluecumber.CluecumberReportPlugin. Classes must have either one (and only one) constructor annotated with @Inject or a zero-argument constructor that is not private.
	  at com.trivago.cluecumber.CluecumberReportPlugin.class(Unknown Source)
	  while locating com.trivago.cluecumber.CluecumberReportPlugin
	
	1 error
		at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:994)
		at com.google.inject.internal.InjectorImpl.getProvider(InjectorImpl.java:951)
		at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1003)
		at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:47)
		at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
		at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:968)
		at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1014)
		at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:964)
		at com.google.inject.Scopes$1$1.get(Scopes.java:59)
		at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:79)
		at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:53)
		at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:243)
		at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:235)
		at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:455)
		at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
		at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
		at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
		at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
		at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:319)
		at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
		at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
		at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
		at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
		at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
		at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
		at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
		at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)

I added plugin to my POM as below:

`  <plugin>
	<groupId>com.trivago.rta</groupId>
	<artifactId>cluecumber-report-plugin</artifactId>
	<version>2.3.4</version>
	<executions>
	  <execution>
		<id>report</id>
		<phase>post-integration-test</phase>
		<goals>
		  <goal>reporting</goal>
		</goals>
	  </execution>
	</executions>
	<configuration>
	  <sourceJsonReportDirectory>${project.build.directory}/cucumber-report</sourceJsonReportDirectory>
	  <generatedHtmlReportDirectory>${project.build.directory}/cluecumber-report</generatedHtmlReportDirectory>
	  <sourceJsonReportDirectory>${project.build.directory}/cucumber-parallel</sourceJsonReportDirectory>
	</configuration>
  </plugin>`

**Additional context**
I understand that it could be a problem with our Bamboo set up however we are not sure. For us its getting difficult to debug in bamboo so any help would be apprceciated.

**Comment by laxersaz** [comment]
I think your server's Maven version is too low. You need at least Maven 3.3.9.

**Comment by motivatedmind** [comment]
That actually helped. Default Maven version in server was older. Changing it to 3.3.9 solved the problem. Thanks a lot !!
