### ISSUE TITLE
NullPointerException while processing cucumber reports without elements

### ISSUE THREAD

**Issue by schmalzi-compax** [trivago/cluecumber-report-plugin#3]
The following NullPointerExceptions happens if a scenario won't get executed because of a tag configuration e.g. @ignore which avoids processing in cucumber.

[ERROR] Failed to execute goal com.trivago.rta:cluecumber-report-plugin:0.0.3:reporting (report) on project testsuite-factory: Execution report of goal com.trivago.rta:cluecumber-report-plugin:0.0.3:reporting failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.trivago.rta:cluecumber-report-plugin:0.0.3:reporting (report) on project testsuite-factory: Execution report of goal com.trivago.rta:cluecumber-report-plugin:0.0.3:reporting failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution report of goal com.trivago.rta:cluecumber-report-plugin:0.0.3:reporting failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.NullPointerException
	at com.trivago.rta.rendering.ReportGenerator.generateReports(ReportGenerator.java:67)
	at CluecumberReportPlugin.execute(CluecumberReportPlugin.java:106)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Cucumber json report which leads to the error is attached.

[cusumber_json_report.zip](https://github.com/trivago/cluecumber-report-plugin/files/1484912/cusumber_json_report.zip)

**Comment by laxersaz** [comment]
Thanks a lot for reporting. It is super helpful to get such a detailed description of the issue! I will look into it on Monday and release a fix asap!

**Comment by schmalzi-compax** [comment]
sounds good, i'll test the fix if it's available. Thank you in advance.

**Comment by laxersaz** [comment]
@schmalzi-compax I just release cluecumber 0.0.4 which handles the reported issues. Please check if everything is alright for you.

**Comment by schmalzi-compax** [comment]
The fix solved the problem, thank you very much.
