### ISSUE TITLE
attachments' could not be created

### ISSUE THREAD

**Issue by magori** [trivago/cluecumber-report-plugin#79]
**Describe the bug**
when y launch this comande:  mvn cluecumber-report:reporting -e

I have this error : org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.trivago.rta:cluecumber-report-plugin:1.2.1:reporting (default-cli) on project affiliation-service-bdd: Path '>D:\workspaces\avs\avs4-bdd\affiliation-service-bdd\target/site/cluec
umber-report/attachments' could not be created.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: com.trivago.rta.exceptions.filesystem.PathCreationException: Path '>D:\workspaces\avs\avs4-bdd\affiliation-service-bdd\target/site/cluecumber-report/attachments' could not be created.
        at com.trivago.rta.filesystem.FileSystemManager.createDirectory(FileSystemManager.java:72)
        at com.trivago.rta.CluecumberReportPlugin.execute(CluecumberReportPlugin.java:108)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more

**Additional context**
I am on Windows

**Comment by laxersaz** [comment]
Please try specifying your path with forward slashes. Currently you have a mixture of backslashes and forward slashes.

**Comment by magori** [comment]
Thanks for the answer. I found my problem.
I left this char ">" in the configuration of the plugin.
<generatedHtmlReportDirectory>**>**${project.build.directory}/site/cluecumber-repor</generatedHtmlReportDirectory>
Sorry for the disagreement
